# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newQRWin.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddNewPassenger(object):
    def setupUi(self, AddNewPassenger):
        AddNewPassenger.setObjectName("AddNewPassenger")
        AddNewPassenger.resize(1022, 597)
        self.centralwidget = QtWidgets.QWidget(AddNewPassenger)
        self.centralwidget.setObjectName("centralwidget")
        self.txt_name_code = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_name_code.setGeometry(QtCore.QRect(180, 170, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txt_name_code.setFont(font)
        self.txt_name_code.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.txt_name_code.setText("")
        self.txt_name_code.setPlaceholderText("")
        self.txt_name_code.setObjectName("txt_name_code")
        self.txt_age = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_age.setGeometry(QtCore.QRect(180, 220, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txt_age.setFont(font)
        self.txt_age.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.txt_age.setText("")
        self.txt_age.setPlaceholderText("")
        self.txt_age.setObjectName("txt_age")
        self.txt_number = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_number.setGeometry(QtCore.QRect(180, 270, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txt_number.setFont(font)
        self.txt_number.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.txt_number.setText("")
        self.txt_number.setPlaceholderText("")
        self.txt_number.setObjectName("txt_number")
        self.txt_address = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_address.setGeometry(QtCore.QRect(180, 320, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txt_address.setFont(font)
        self.txt_address.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.txt_address.setText("")
        self.txt_address.setPlaceholderText("")
        self.txt_address.setObjectName("txt_address")
        self.btn_generate = QtWidgets.QPushButton(self.centralwidget)
        self.btn_generate.setGeometry(QtCore.QRect(80, 380, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_generate.setFont(font)
        self.btn_generate.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.btn_generate.setObjectName("btn_generate")
        self.btn_clear = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear.setGeometry(QtCore.QRect(310, 380, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_clear.setFont(font)
        self.btn_clear.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.btn_clear.setObjectName("btn_clear")
        self.qr_code_img = QtWidgets.QLabel(self.centralwidget)
        self.qr_code_img.setGeometry(QtCore.QRect(710, 170, 211, 201))
        self.qr_code_img.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.qr_code_img.setText("")
        self.qr_code_img.setObjectName("qr_code_img")
        self.btn_print = QtWidgets.QPushButton(self.centralwidget)
        self.btn_print.setGeometry(QtCore.QRect(710, 380, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_print.setFont(font)
        self.btn_print.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.btn_print.setObjectName("btn_print")
        self.back_btn = QtWidgets.QPushButton(self.centralwidget)
        self.back_btn.setGeometry(QtCore.QRect(630, 460, 361, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.back_btn.setFont(font)
        self.back_btn.setStyleSheet("background-color: rgb(32, 56, 100);\n"
"color: rgb(255, 255, 255);")
        self.back_btn.setObjectName("back_btn")
        self.bg_lbl = QtWidgets.QLabel(self.centralwidget)
        self.bg_lbl.setGeometry(QtCore.QRect(0, -10, 1021, 571))
        self.bg_lbl.setText("")
        self.bg_lbl.setPixmap(QtGui.QPixmap("GenerateQRbg.png"))
        self.bg_lbl.setScaledContents(True)
        self.bg_lbl.setObjectName("bg_lbl")
        self.btn_driver = QtWidgets.QPushButton(self.centralwidget)
        self.btn_driver.setGeometry(QtCore.QRect(690, 10, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_driver.setFont(font)
        self.btn_driver.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.btn_driver.setObjectName("btn_driver")
        self.lbl_msg = QtWidgets.QLabel(self.centralwidget)
        self.lbl_msg.setGeometry(QtCore.QRect(50, 470, 521, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_msg.setFont(font)
        self.lbl_msg.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_msg.setText("")
        self.lbl_msg.setObjectName("lbl_msg")
        self.lbl_msg_2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_msg_2.setGeometry(QtCore.QRect(40, 160, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_msg_2.setFont(font)
        self.lbl_msg_2.setStyleSheet("")
        self.lbl_msg_2.setObjectName("lbl_msg_2")
        self.lbl_msg_3 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_msg_3.setGeometry(QtCore.QRect(40, 210, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_msg_3.setFont(font)
        self.lbl_msg_3.setStyleSheet("")
        self.lbl_msg_3.setObjectName("lbl_msg_3")
        self.lbl_msg_4 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_msg_4.setGeometry(QtCore.QRect(40, 270, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_msg_4.setFont(font)
        self.lbl_msg_4.setStyleSheet("")
        self.lbl_msg_4.setObjectName("lbl_msg_4")
        self.lbl_msg_5 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_msg_5.setGeometry(QtCore.QRect(40, 320, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_msg_5.setFont(font)
        self.lbl_msg_5.setStyleSheet("")
        self.lbl_msg_5.setObjectName("lbl_msg_5")
        self.lbl_msg_6 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_msg_6.setGeometry(QtCore.QRect(40, 10, 551, 71))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_msg_6.setFont(font)
        self.lbl_msg_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_msg_6.setObjectName("lbl_msg_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(650, 110, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 110, 531, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.bg_lbl.raise_()
        self.txt_name_code.raise_()
        self.txt_age.raise_()
        self.txt_number.raise_()
        self.txt_address.raise_()
        self.btn_generate.raise_()
        self.btn_clear.raise_()
        self.qr_code_img.raise_()
        self.btn_print.raise_()
        self.back_btn.raise_()
        self.btn_driver.raise_()
        self.lbl_msg.raise_()
        self.lbl_msg_2.raise_()
        self.lbl_msg_3.raise_()
        self.lbl_msg_4.raise_()
        self.lbl_msg_5.raise_()
        self.lbl_msg_6.raise_()
        self.label.raise_()
        self.label_2.raise_()
        AddNewPassenger.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AddNewPassenger)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1022, 26))
        self.menubar.setObjectName("menubar")
        AddNewPassenger.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AddNewPassenger)
        self.statusbar.setObjectName("statusbar")
        AddNewPassenger.setStatusBar(self.statusbar)

        self.retranslateUi(AddNewPassenger)
        QtCore.QMetaObject.connectSlotsByName(AddNewPassenger)

    def retranslateUi(self, AddNewPassenger):
        _translate = QtCore.QCoreApplication.translate
        AddNewPassenger.setWindowTitle(_translate("AddNewPassenger", "ADD Passenger"))
        self.btn_generate.setText(_translate("AddNewPassenger", "GENERATE QR"))
        self.btn_clear.setText(_translate("AddNewPassenger", "CLEAR"))
        self.btn_print.setText(_translate("AddNewPassenger", "PRINT"))
        self.back_btn.setText(_translate("AddNewPassenger", "BACK TO MAIN MENU"))
        self.btn_driver.setText(_translate("AddNewPassenger", "DRIVER? CLICK HERE!!"))
        self.lbl_msg_2.setText(_translate("AddNewPassenger", "NAME"))
        self.lbl_msg_3.setText(_translate("AddNewPassenger", "Age"))
        self.lbl_msg_4.setText(_translate("AddNewPassenger", "Contact #"))
        self.lbl_msg_5.setText(_translate("AddNewPassenger", "Address"))
        self.lbl_msg_6.setText(_translate("AddNewPassenger", "UV EXPRESS TERMINAL"))
        self.label.setText(_translate("AddNewPassenger", "PASSENGER QR CODE"))
        self.label_2.setText(_translate("AddNewPassenger", "PASSENGER INFORMATION"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddNewPassenger = QtWidgets.QMainWindow()
    ui = Ui_AddNewPassenger()
    ui.setupUi(AddNewPassenger)
    AddNewPassenger.show()
    sys.exit(app.exec_())
