# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newRFWin.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_rfWin(object):
    def setupUi(self, rfWin):
        rfWin.setObjectName("rfWin")
        rfWin.resize(1021, 595)
        self.centralwidget = QtWidgets.QWidget(rfWin)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 170, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 290, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 350, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.nameRF_blank = QtWidgets.QLineEdit(self.centralwidget)
        self.nameRF_blank.setGeometry(QtCore.QRect(290, 160, 451, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.nameRF_blank.setFont(font)
        self.nameRF_blank.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.nameRF_blank.setObjectName("nameRF_blank")
        self.plateRF_blank = QtWidgets.QLineEdit(self.centralwidget)
        self.plateRF_blank.setGeometry(QtCore.QRect(290, 280, 451, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.plateRF_blank.setFont(font)
        self.plateRF_blank.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.plateRF_blank.setObjectName("plateRF_blank")
        self.codRF_blank = QtWidgets.QLineEdit(self.centralwidget)
        self.codRF_blank.setGeometry(QtCore.QRect(290, 340, 451, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.codRF_blank.setFont(font)
        self.codRF_blank.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.codRF_blank.setObjectName("codRF_blank")
        self.writeRF_btn = QtWidgets.QPushButton(self.centralwidget)
        self.writeRF_btn.setGeometry(QtCore.QRect(650, 430, 341, 111))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.writeRF_btn.setFont(font)
        self.writeRF_btn.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.writeRF_btn.setObjectName("writeRF_btn")
        self.statusRF_lbl = QtWidgets.QLabel(self.centralwidget)
        self.statusRF_lbl.setGeometry(QtCore.QRect(270, 20, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.statusRF_lbl.setFont(font)
        self.statusRF_lbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.statusRF_lbl.setText("")
        self.statusRF_lbl.setObjectName("statusRF_lbl")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 1021, 561))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("writeRFbg.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(770, 20, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.pushButton.setObjectName("pushButton")
        self.contactRF_blank = QtWidgets.QLineEdit(self.centralwidget)
        self.contactRF_blank.setGeometry(QtCore.QRect(290, 220, 451, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.contactRF_blank.setFont(font)
        self.contactRF_blank.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.contactRF_blank.setObjectName("contactRF_blank")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 230, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 30, 471, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.status_lbl = QtWidgets.QLabel(self.centralwidget)
        self.status_lbl.setGeometry(QtCore.QRect(10, 430, 581, 111))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.status_lbl.setFont(font)
        self.status_lbl.setStyleSheet("background-color: rgb(32, 56, 100);\n"
"color: rgb(255, 255, 255);")
        self.status_lbl.setText("")
        self.status_lbl.setObjectName("status_lbl")
        self.label_4.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.nameRF_blank.raise_()
        self.plateRF_blank.raise_()
        self.codRF_blank.raise_()
        self.writeRF_btn.raise_()
        self.statusRF_lbl.raise_()
        self.pushButton.raise_()
        self.contactRF_blank.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.status_lbl.raise_()
        rfWin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(rfWin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1021, 26))
        self.menubar.setObjectName("menubar")
        rfWin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(rfWin)
        self.statusbar.setObjectName("statusbar")
        rfWin.setStatusBar(self.statusbar)

        self.retranslateUi(rfWin)
        QtCore.QMetaObject.connectSlotsByName(rfWin)

    def retranslateUi(self, rfWin):
        _translate = QtCore.QCoreApplication.translate
        rfWin.setWindowTitle(_translate("rfWin", "OVERWRITE RFID"))
        self.label.setText(_translate("rfWin", "NAME:"))
        self.label_2.setText(_translate("rfWin", "PLATE NO:"))
        self.label_3.setText(_translate("rfWin", "CODING DAY:"))
        self.writeRF_btn.setText(_translate("rfWin", "WRITE"))
        self.pushButton.setText(_translate("rfWin", "Back To Main"))
        self.label_5.setText(_translate("rfWin", "CONTACT NO:"))
        self.label_6.setText(_translate("rfWin", "UV EXPRESS TERMINAL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    rfWin = QtWidgets.QMainWindow()
    ui = Ui_rfWin()
    ui.setupUi(rfWin)
    rfWin.show()
    sys.exit(app.exec_())
